services:
  openai-node:
    build:
      context: .
    env_file: ".env"
    command: ["python3", "main.py" ]
    restart: always
    networks:
      - dormintlab_openai_node
    depends_on:
      - openai-proxy

  openai-proxy:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: ".env"
    command: [ "ss-local", "-c", "/etc/shadowsocks-libev/myvpn.json" ]
    restart: always
    networks:
      - dormintlab_openai_node
    volumes:
      - "/etc/shadowsocks-libev/myvpn.json:/etc/shadowsocks-libev/myvpn.json"

networks:
  dormintlab_openai_node:
    external: false
    name: dormintlab_openai_node
