services:
  openai-node:
    build:
      context: .
    command: ["python3", "main.py" ]
    ports:
      - "8351:8351"
    restart: always
    networks:
      - dormintlab_openai_node
    depends_on:
      - openai-proxy

  openai-proxy:
    build:
      context: .
      dockerfile: Dockerfile
    command: [ "ss-local", "-c", "/etc/shadowsocks-libev/myvpn.json" ]
    restart: always
    networks:
      - dormintlab_openai_node
    volumes:
      - "/etc/shadowsocks-libev/myvpn.json:/etc/shadowsocks-libev/myvpn.json"

networks:
  dormintlab_openai_node:
    external: false
    name: dormintlab_openai_node
